"""Remove redundant start_date and contribution_type fields

Revision ID: f79b481cd9b5
Revises: 62172e625aae
Create Date: 2025-12-12 22:46:38.516959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f79b481cd9b5'
down_revision: Union[str, Sequence[str], None] = '62172e625aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
